import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import SessionProviderWrapper from "./components/SessionProviderWrapper";
import localFont from "next/font/local";
const myFont = localFont({
  src: "../../public/font/font.ttf",
  variable: "--font-cal-sans",
  display: "swap",
  weight: "600",
  style: "normal",
  fallback: ["sans-serif"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} antialiased`}
      >
        <SessionProviderWrapper>
        <Navbar />
        {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
